		TRUNCATE TABLE BeanDistribute
		TRUNCATE TABLE BeanReport
		TRUNCATE TABLE ChargeDistribute
		TRUNCATE TABLE CurrencyDistribute
		TRUNCATE TABLE CurrencyReport
		TRUNCATE TABLE GameReport
		TRUNCATE TABLE GoldDistribute
		TRUNCATE TABLE LoginReport
		TRUNCATE TABLE MatchGameReport
		TRUNCATE TABLE NewAdReport
		TRUNCATE TABLE NewBeanReport
		TRUNCATE TABLE NewChargeReport
		TRUNCATE TABLE NewCurrencyReport
		TRUNCATE TABLE NewExtendChannelReport
		TRUNCATE TABLE NewGameReport
		TRUNCATE TABLE NewQmallReport
		TRUNCATE TABLE NewRegReport
		TRUNCATE TABLE NewSubAccReport
		TRUNCATE TABLE NewUserReport
		TRUNCATE TABLE PayChannelReport
		TRUNCATE TABLE PromotReport
		TRUNCATE TABLE RegistReport
		TRUNCATE TABLE RoomCardReport
		TRUNCATE TABLE SceneReport
		TRUNCATE TABLE SilverDistribute
		TRUNCATE TABLE StrongboxRecord
		TRUNCATE TABLE SystemLog
		TRUNCATE TABLE UserActive
		TRUNCATE TABLE UserDayCharge
	